### ISSUE TITLE
Scope and usability of the studio?

### ISSUE THREAD

**Issue by mpizenberg** [protofire/Cardano-Developer-Studio#10]
Hi, I just stumbled upon this because I’m reviewing some Catalyst proposals. I’ve never heard of this project before, and it doesn’t seem to be pushed by any of its participants on other Cardano public channel?

Isn’t the goal of this to be usable by the community at large?

**Comment by Fran-cio** [comment]
Thank you for your message and for taking the time to review our proposal! You’re absolutely right that visibility and community engagement are key, especially for projects aimed at the broader Cardano ecosystem.

We recently released the project, and while we’ve discussed it with a few members of the Cardano community, we recognize that there's room to improve in terms of making it more widely known and accessible. Our next step is to actively promote it across public channels and social media, so that more people can benefit from it and contribute to its development.

We’re committed to enhancing our outreach and ensuring that this project becomes a valuable resource for the entire Cardano community. Your feedback is appreciated, and we look forward to expanding our engagement!

If you have any further questions about the project, don’t hesitate to ask. Best regards.
